import { environment } from './src/environments/environment';

export var Config = (function () {
  // -------------------------------------
  // OBRIGATÓRIO
  // Disponível em https://dev.facetec.com/account
  // NOTA: Este campo é auto populado pelo arquivo environment importado na linha 1.
  var DeviceKeyIdentifier = environment.DeviceKeyIdentifier;

  // -------------------------------------
  // OBRIGATÓRIO
  // URL para chamar o processo de sessão do SDK da FaceTec.
  // Em produção, você provavelmente lidará com solicitações de rede em outro lugar e sem o uso dessa variável.
  // Acesse https://dev.facetec.com/security-best-practices?link=facetec-server-rest-endpoint-security para maiores informações.
  // NOTA: Este campo é auto populado pelo arquivo environment importado na linha 1.
  var BaseURL = environment.BaseURL;

  // -------------------------------------
  // OBRIGATÓRIO
  // Chave de Criptografia do FaceScan definido por você em sua aplicação.
  // Acesse https://dev.facetec.com/facemap-encryption-keys para maiores informações.
  // NOTA: Este campo é auto populado pelo arquivo environment importado na linha 1.
  var PublicFaceScanEncryptionKey = environment.PublicFaceScanEncryptionKey;

  // -------------------------------------
  // OBRIGATÓRIO SE: Tiver uma Chave de Produção gerada por você.
  // As chaves de produção são geradas para sua conta assim que todas as etapas em produção forem concluídas.
  // Maiores informações sobre o andamento em produção podem ser encontradas em https://dev.facetec.com/going-production-overview.
  //
  // NOTA:  NÃO codifique isso em seu aplicativo real. Essa variável é codificada no aplicativo apenas para fins de demonstração.
  // Seu aplicativo DEVE fornecer os dados principais por meio de sua própria API. Isso permite que você altere/atualize as chaves sem fazer uma alteração no lado do cliente.
  // Acesse https://dev.facetec.com/licensing?link=integrating-production-licenses para maiores informações.
  var ProductionKeyText = environment.ProductionKeyText;

  // -------------------------------------
  // Método de conveniência para inicializar o SDK da FaceTec.
  // NOTA: Esta função é preenchida automaticamente pelo SDK da FaceTec Configuration Wizard com base em suas personalizações de interface do usuário que você escolheu na GUI do assistente de configuração.

  function initializeFromAutogeneratedConfig(FaceTecSDK, callback) {
    FaceTecSDK.initializeInProductionMode(
      ProductionKeyText,
      this.DeviceKeyIdentifier,
      this.PublicFaceScanEncryptionKey,
      function (initializedSuccessfully) {
        callback(initializedSuccessfully);
      }
    );
  }

  // Este aplicativo pode modificar a personalização para demonstrar diferentes preferências de aparência/sensação
  // NOTA: Esta função é preenchida automaticamente pelo FaceTec SDK Configuration Wizard com base em suas personalizações de interface do usuário que você escolheu na GUI do Configuration Wizard.
  function retrieveConfigurationWizardCustomization(FaceTecSDK) {
    var sdkImageDirectory = 'assets/core-sdk/FaceTec_images';

    // Para personalização de cores
    var outerBackgroundColor = '#ffffff';
    var frameColor = '#ffffff';
    var borderColor = '#417FB2';
    var ovalColor = '#417FB2';
    var dualSpinnerColor = '#417FB2';
    var textColor = '#417FB2';
    var buttonAndFeedbackBarColor = '#417FB2';
    var buttonAndFeedbackBarTextColor = '#ffffff';
    var buttonColorHighlight = '#396E99';
    var buttonColorDisabled = '#B9CCDE';

    // Para personalização do raio do canto do quadro
    let frameCornerRadius = '20px';

    // Para personalização do botão Cancelar
    var cancelButtonImage = `${sdkImageDirectory}/FaceTec_cancel.png`;
    var cancelButtonLocation = FaceTecSDK.FaceTecCancelButtonLocation.TopLeft;

    // Para personalização de imagem
    var yourAppLogoImage = `${sdkImageDirectory}/FaceTec_your_app_logo.png`;
    var securityWatermarkImage =
      FaceTecSDK.FaceTecSecurityWatermarkImage.FaceTec;

    // Definindo uma personalização padrão
    var defaultCustomization = new FaceTecSDK.FaceTecCustomization();

    // Definindo personalização do quadro
    defaultCustomization.frameCustomization.borderCornerRadius =
      frameCornerRadius;
    defaultCustomization.frameCustomization.backgroundColor = frameColor;
    defaultCustomization.frameCustomization.borderColor = borderColor;

    // Definindo personalização de sobreposição
    defaultCustomization.overlayCustomization.brandingImage = yourAppLogoImage;
    defaultCustomization.overlayCustomization.backgroundColor =
      outerBackgroundColor;

    // Definindo personalização de orientação
    defaultCustomization.guidanceCustomization.backgroundColors = frameColor;
    defaultCustomization.guidanceCustomization.foregroundColor = textColor;
    defaultCustomization.guidanceCustomization.buttonBackgroundNormalColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.guidanceCustomization.buttonBackgroundDisabledColor =
      buttonColorDisabled;
    defaultCustomization.guidanceCustomization.buttonBackgroundHighlightColor =
      buttonColorHighlight;
    defaultCustomization.guidanceCustomization.buttonTextNormalColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.guidanceCustomization.buttonTextDisabledColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.guidanceCustomization.buttonTextHighlightColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.guidanceCustomization.retryScreenImageBorderColor =
      borderColor;
    defaultCustomization.guidanceCustomization.retryScreenOvalStrokeColor =
      borderColor;

    // Definir personalização da área oval
    defaultCustomization.ovalCustomization.strokeColor = ovalColor;
    defaultCustomization.ovalCustomization.progressColor1 = dualSpinnerColor;
    defaultCustomization.ovalCustomization.progressColor2 = dualSpinnerColor;

    // Definindo personalização de comentários
    defaultCustomization.feedbackCustomization.backgroundColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.feedbackCustomization.textColor =
      buttonAndFeedbackBarTextColor;

    // Definindo personalização do botão Cancelar
    defaultCustomization.cancelButtonCustomization.customImage =
      cancelButtonImage;
    defaultCustomization.cancelButtonCustomization.location =
      cancelButtonLocation;

    // Definir personalização de marca d'água de segurança
    defaultCustomization.securityWatermarkCustomization.setSecurityWatermarkImage(
      securityWatermarkImage
    );

    // Definindo personalização da tela de resultados
    defaultCustomization.resultScreenCustomization.backgroundColors =
      frameColor;
    defaultCustomization.resultScreenCustomization.foregroundColor = textColor;
    defaultCustomization.resultScreenCustomization.activityIndicatorColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.resultScreenCustomization.resultAnimationBackgroundColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.resultScreenCustomization.resultAnimationForegroundColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.resultScreenCustomization.uploadProgressFillColor =
      buttonAndFeedbackBarColor;

    // Definindo personalização de digitalização de ID
    defaultCustomization.idScanCustomization.selectionScreenBackgroundColors =
      frameColor;
    defaultCustomization.idScanCustomization.selectionScreenForegroundColor =
      textColor;
    defaultCustomization.idScanCustomization.reviewScreenBackgroundColors =
      frameColor;
    defaultCustomization.idScanCustomization.reviewScreenForegroundColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.reviewScreenTextBackgroundColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.idScanCustomization.captureScreenForegroundColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.captureScreenTextBackgroundColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.idScanCustomization.buttonBackgroundNormalColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.idScanCustomization.buttonBackgroundDisabledColor =
      buttonColorDisabled;
    defaultCustomization.idScanCustomization.buttonBackgroundHighlightColor =
      buttonColorHighlight;
    defaultCustomization.idScanCustomization.buttonTextNormalColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.buttonTextDisabledColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.buttonTextHighlightColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.captureScreenBackgroundColor =
      frameColor;
    defaultCustomization.idScanCustomization.captureFrameStrokeColor =
      borderColor;

    // Definindo personalização de carregamento inicial
    defaultCustomization.initialLoadingAnimationCustomization.backgroundColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.initialLoadingAnimationCustomization.foregroundColor =
      buttonAndFeedbackBarColor;

    return defaultCustomization;
  }

  function retrieveLowLightConfigurationWizardCustomization(FaceTecSDK) {
    var defaultCustomization =
      retrieveConfigurationWizardCustomization(FaceTecSDK);
    this.currentLowLightCustomization = defaultCustomization;
    return defaultCustomization;
  }

  function retrieveDynamicDimmingConfigurationWizardCustomization(FaceTecSDK) {
    var defaultCustomization =
      retrieveConfigurationWizardCustomization(FaceTecSDK);
    this.currentDynamicDimmingCustomization = defaultCustomization;
    return defaultCustomization;
  }

  var currentCustomization;
  var currentLowLightCustomization;
  var currentDynamicDimmingCustomization;

  // -------------------------------------
  // Booleano para indicar que o FaceTec SDK Configuration Wizard foi usado para gerar este arquivo.
  // Neste aplicativo de exemplo, se esta variável for verdadeira, um "Tema do assistente de configuração" (Config Wizard Theme) será adicionado ao Design Showcase deste aplicativo,
  // e escolher esta opção definirá as personalizações de UI/UX do FaceTec SDK para as personalizações que você selecionou no
  // Assistente de configuração.
  var wasSDKConfiguredWithConfigWizard = true;

  return {
    wasSDKConfiguredWithConfigWizard,
    DeviceKeyIdentifier,
    BaseURL,
    PublicFaceScanEncryptionKey,
    ProductionKeyText,
    initializeFromAutogeneratedConfig,
    currentCustomization,
    currentLowLightCustomization,
    currentDynamicDimmingCustomization,
    retrieveConfigurationWizardCustomization,
    retrieveLowLightConfigurationWizardCustomization,
    retrieveDynamicDimmingConfigurationWizardCustomization,
  };
})();
