export declare var Config: {
    wasSDKConfiguredWithConfigWizard: boolean;
    DeviceKeyIdentifier: string;
    BaseURL: string;
    PublicFaceScanEncryptionKey: string;
    initializeFromAutogeneratedConfig: (FaceTecSDK: any, callback: any) => void;
    currentCustomization: any;
    currentLowLightCustomization: any;
    currentDynamicDimmingCustomization: any;
    retrieveConfigurationWizardCustomization: (FaceTecSDK: any) => any;
    retrieveLowLightConfigurationWizardCustomization: (FaceTecSDK: any) => any;
    retrieveDynamicDimmingConfigurationWizardCustomization: (FaceTecSDK: any) => any;
};